version: "3"

volumes:
  student-grade:
    driver: local
services:
  mysql-service:
    image: "mysql:5.7.30"
    networks:
      - grade-network
    container_name: student-grade-mysql
    volumes:
      - student-grade:/var/lib/mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --disable-partition-engine-check
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - grade-network
    depends_on:
      - mysql-service

networks:
  grade-network:
    driver: bridge
